export const MOCK_ENQUIRIES = [
  {
    id: 1001,
    customer_name: 'Angelique Morse',
    package_name: 'Umrah Economy 15 Days',
    pax_count: 2,
    status: 'Hot',
    conversion_status: 'Pending',
    quote_amount: 185000,
    currency_code: 'INR',
    agent_name: 'Aadil Hussain',
    created_at: '2025-01-12',
  },
  {
    id: 1002,
    customer_name: 'Ariana Lang',
    package_name: 'Umrah Premium 21 Days',
    pax_count: 4,
    status: 'Warm',
    conversion_status: 'Converted',
    quote_amount: 420000,
    currency_code: 'INR',
    agent_name: 'Imran Khan',
    created_at: '2025-01-11',
  },
  {
    id: 1003,
    customer_name: 'Ethan Hunt',
    package_name: 'Hajj Short Package',
    pax_count: 1,
    status: 'Cold',
    conversion_status: 'Lost',
    quote_amount: 0,
    currency_code: 'INR',
    agent_name: 'Salman Ali',
    created_at: '2025-01-10',
  },
  {
    id: 1004,
    customer_name: 'Fatima Noor',
    package_name: 'Umrah Economy 10 Days',
    pax_count: 3,
    status: 'Hot',
    conversion_status: 'Pending',
    quote_amount: 260000,
    currency_code: 'INR',
    agent_name: 'Aadil Hussain',
    created_at: '2025-01-09',
  },
  {
    id: 1005,
    customer_name: 'Mohammed Rahman',
    package_name: 'Umrah Deluxe 15 Days',
    pax_count: 2,
    status: 'Warm',
    conversion_status: 'Converted',
    quote_amount: 310000,
    currency_code: 'INR',
    agent_name: 'Imran Khan',
    created_at: '2025-01-08',
  },
  {
    id: 1006,
    customer_name: 'Sara Williams',
    package_name: 'Umrah Economy 21 Days',
    pax_count: 5,
    status: 'Cold',
    conversion_status: 'Pending',
    quote_amount: 450000,
    currency_code: 'INR',
    agent_name: 'Neha Sharma',
    created_at: '2025-01-08',
  },
  {
    id: 1007,
    customer_name: 'Ahmed Khan',
    package_name: 'Hajj Premium Package',
    pax_count: 2,
    status: 'Hot',
    conversion_status: 'Converted',
    quote_amount: 850000,
    currency_code: 'INR',
    agent_name: 'Salman Ali',
    created_at: '2025-01-07',
  },
  {
    id: 1008,
    customer_name: 'Zainab Ali',
    package_name: 'Umrah Economy 7 Days',
    pax_count: 1,
    status: 'Warm',
    conversion_status: 'Pending',
    quote_amount: 98000,
    currency_code: 'INR',
    agent_name: 'Neha Sharma',
    created_at: '2025-01-07',
  },
  {
    id: 1009,
    customer_name: 'Bilal Ahmad',
    package_name: 'Umrah Premium 10 Days',
    pax_count: 3,
    status: 'Hot',
    conversion_status: 'Pending',
    quote_amount: 330000,
    currency_code: 'INR',
    agent_name: 'Aadil Hussain',
    created_at: '2025-01-06',
  },
  {
    id: 1010,
    customer_name: 'Hina Qureshi',
    package_name: 'Umrah Economy 15 Days',
    pax_count: 2,
    status: 'Cold',
    conversion_status: 'Lost',
    quote_amount: 0,
    currency_code: 'INR',
    agent_name: 'Imran Khan',
    created_at: '2025-01-06',
  },
  {
    id: 1011,
    customer_name: 'Omar Farooq',
    package_name: 'Hajj Economy Package',
    pax_count: 4,
    status: 'Warm',
    conversion_status: 'Pending',
    quote_amount: 620000,
    currency_code: 'INR',
    agent_name: 'Salman Ali',
    created_at: '2025-01-05',
  },
  {
    id: 1012,
    customer_name: 'Noor Jahan',
    package_name: 'Umrah Deluxe 21 Days',
    pax_count: 2,
    status: 'Hot',
    conversion_status: 'Converted',
    quote_amount: 510000,
    currency_code: 'INR',
    agent_name: 'Neha Sharma',
    created_at: '2025-01-05',
  },
  {
    id: 1013,
    customer_name: 'Yusuf Patel',
    package_name: 'Umrah Economy 10 Days',
    pax_count: 1,
    status: 'Cold',
    conversion_status: 'Lost',
    quote_amount: 0,
    currency_code: 'INR',
    agent_name: 'Aadil Hussain',
    created_at: '2025-01-04',
  },
  {
    id: 1014,
    customer_name: 'Khadija Ansari',
    package_name: 'Umrah Premium 15 Days',
    pax_count: 3,
    status: 'Warm',
    conversion_status: 'Pending',
    quote_amount: 360000,
    currency_code: 'INR',
    agent_name: 'Imran Khan',
    created_at: '2025-01-04',
  },
  {
    id: 1015,
    customer_name: 'Abdul Rehman',
    package_name: 'Hajj Long Stay Package',
    pax_count: 2,
    status: 'Hot',
    conversion_status: 'Pending',
    quote_amount: 920000,
    currency_code: 'INR',
    agent_name: 'Salman Ali',
    created_at: '2025-01-03',
  },
  {
    id: 1016,
    customer_name: 'Maryam Siddiqui',
    package_name: 'Umrah Economy 21 Days',
    pax_count: 4,
    status: 'Warm',
    conversion_status: 'Converted',
    quote_amount: 410000,
    currency_code: 'INR',
    agent_name: 'Neha Sharma',
    created_at: '2025-01-03',
  },
  {
    id: 1017,
    customer_name: 'Faisal Mehmood',
    package_name: 'Umrah Economy 7 Days',
    pax_count: 2,
    status: 'Cold',
    conversion_status: 'Lost',
    quote_amount: 0,
    currency_code: 'INR',
    agent_name: 'Aadil Hussain',
    created_at: '2025-01-02',
  },
  {
    id: 1018,
    customer_name: 'Sana Malik',
    package_name: 'Umrah Premium 21 Days',
    pax_count: 3,
    status: 'Hot',
    conversion_status: 'Pending',
    quote_amount: 470000,
    currency_code: 'INR',
    agent_name: 'Imran Khan',
    created_at: '2025-01-02',
  },
  {
    id: 1019,
    customer_name: 'Ibrahim Sheikh',
    package_name: 'Hajj Economy Package',
    pax_count: 5,
    status: 'Warm',
    conversion_status: 'Pending',
    quote_amount: 780000,
    currency_code: 'INR',
    agent_name: 'Salman Ali',
    created_at: '2025-01-01',
  },
  {
    id: 1020,
    customer_name: 'Ayesha Farhan',
    package_name: 'Umrah Deluxe 10 Days',
    pax_count: 2,
    status: 'Hot',
    conversion_status: 'Converted',
    quote_amount: 295000,
    currency_code: 'INR',
    agent_name: 'Neha Sharma',
    created_at: '2025-01-01',
  },
];
